insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Guest', false, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Sir Voyager', true, true, 'password', true, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Domax', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Snotskovl', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Kongen', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Sir Spicion', false, false, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('BadAssBoss', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Brother', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('King Martin', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Baltazar', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Nicedam', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Aragon', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Holger Danske', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Tincan', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('NomaticDK', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Thhinuviel', false, false, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Sofus', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Chris', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Hammer', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Engberg', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('TheAmazingLord', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Casigan', false, false, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Dsk44', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Jig', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Baby kamyne', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Kipp', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Humack', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Ringle', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('HAMkamSAM', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Gnu', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Grgh', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('DasRotePferd', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Tim', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Moes', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Kook', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Pandekagemester', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Jinks', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('bSse', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Java', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Lord Julle', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Garm', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('King Marius', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Nick', false, false, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Master Nitten', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Nanna', false, false, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('ZoZoGamer', false, false, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('-!-Skum-!-', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Damp', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Sha', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Rasmus', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Jeppe', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Vunde', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Roadkill', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('ZWOOM', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Eldar132', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Lasse', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Nederen', true, true, '', false, 1);

insert into fruit (name) values ('Cherry');
insert into fruit (name) values ('Apple');
insert into fruit (name) values ('Banana');

insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', true, 1, 'Sir Voyager', '2018-12-25 19:20:00', 120463, 27);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', true, 1, 'Sir Voyager', '2018-12-25 19:20:00', 114954, 12);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', true, 1, 'Sir Voyager', '2018-12-25 19:20:00', 110870, 51);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', true, 1, 'Sir Voyager', '2018-12-25 19:20:00', 109685, 9);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', true, 1, 'Sir Voyager', '2018-12-25 19:20:00', 101791, 2);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', true, 1, 'Sir Voyager', '2018-12-25 19:20:00', 99282, 5);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', true, 1, 'Sir Voyager', '2018-12-25 19:20:00', 96932, 4);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', true, 1, 'Sir Voyager', '2018-12-25 19:20:00', 92148, 15);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', true, 1, 'Sir Voyager', '2018-12-25 19:20:00', 91238, 13);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', true, 1, 'Sir Voyager', '2018-12-25 19:20:00', 88939, 14);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', true, 1, 'Sir Voyager', '2018-12-25 19:20:00', 80414, 3);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', true, 1, 'Sir Voyager', '2018-12-25 19:20:00', 68762, 7);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', true, 1, 'Sir Voyager', '2018-12-25 19:20:00', 59045, 47);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', true, 1, 'Sir Voyager', '2018-12-25 19:20:00', 58004, 19);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', true, 1, 'Sir Voyager', '2018-12-25 19:20:00', 57551, 28);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', true, 1, 'Sir Voyager', '2018-12-25 19:20:00', 47830, 10);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', true, 1, 'Sir Voyager', '2018-12-25 19:20:00', 46902, 17);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', true, 1, 'Sir Voyager', '2018-12-25 19:20:00', 38025, 11);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', true, 1, 'Sir Voyager', '2018-12-25 19:20:00', 36436, 25);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', true, 1, 'Sir Voyager', '2018-12-25 19:20:00', 35474, 34);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', true, 1, 'Sir Voyager', '2018-12-25 19:20:00', 34826, 20);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', true, 1, 'Sir Voyager', '2018-12-25 19:20:00', 33703, 36);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', true, 1, 'Sir Voyager', '2018-12-25 19:20:00', 32010, 30);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', true, 1, 'Sir Voyager', '2018-12-25 19:20:00', 31451, 18);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', true, 1, 'Sir Voyager', '2018-12-25 19:20:00', 30079, 21);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', true, 1, 'Sir Voyager', '2018-12-25 19:20:00', 30047, 26);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', true, 1, 'Sir Voyager', '2018-12-25 19:20:00', 26393, 35);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', true, 1, 'Sir Voyager', '2018-12-25 19:20:00', 26215, 31);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', true, 1, 'Sir Voyager', '2018-12-25 19:20:00', 25240, 32);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', true, 1, 'Sir Voyager', '2018-12-25 19:20:00', 22208, 49);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', true, 1, 'Sir Voyager', '2018-12-25 19:20:00', 19738, 23);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', true, 1, 'Sir Voyager', '2018-12-25 19:20:00', 16937, 41);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', true, 1, 'Sir Voyager', '2018-12-25 19:20:00', 15381, 52);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', false, 1, 'Sir Voyager', '2018-12-25 19:20:00', 25339, 37);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', false, 1, 'Sir Voyager', '2018-12-25 19:20:00', 18172, 39);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', false, 1, 'Sir Voyager', '2018-12-25 19:20:00', 18164, 29);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', false, 1, 'Sir Voyager', '2018-12-25 19:20:00', 12115, 53);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', false, 1, 'Sir Voyager', '2018-12-25 19:20:00', 10372, 54);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', false, 1, 'Sir Voyager', '2018-12-25 19:20:00', 9854, 55);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', false, 1, 'Sir Voyager', '2018-12-25 19:20:00', 9814, 24);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', false, 1, 'Sir Voyager', '2018-12-25 19:20:00', 9150, 38);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', false, 1, 'Sir Voyager', '2018-12-25 19:20:00', 8453, 33);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', false, 1, 'Sir Voyager', '2018-12-25 19:20:00', 7196, 44);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', false, 1, 'Sir Voyager', '2018-12-25 19:20:00', 5418, 50);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', false, 1, 'Sir Voyager', '2018-12-25 19:20:00', 5266, 40);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', false, 1, 'Sir Voyager', '2018-12-25 19:20:00', 4487, 48);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', false, 1, 'Sir Voyager', '2018-12-25 19:20:00', 4149, 8);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', false, 1, 'Sir Voyager', '2018-12-25 19:20:00', 3457, 42);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', false, 1, 'Sir Voyager', '2018-12-25 19:20:00', 2811, 56);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', false, 1, 'Sir Voyager', '2018-12-25 19:20:00', 830, 57);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-25', false, 1, 'Sir Voyager', '2018-12-25 19:20:00', 0, 1);


insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A1', 'Legendary bow level 40', 1, true, false, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B1', 'Legendary armor level 62', 2, true, false, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A2', 'Legendary armor level 92', 3, true, false, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A11', '2 purple shards', 4, true, true, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B11', '2 purple shards', 5, true, true, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A12', '2 purple shards', 6, true, true, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B2', 'Epic mace level 79', 7, true, false, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A3', 'Epic resurrect orb level 64', 8, true, false, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B3', 'Epic bow level 74', 9, true, false, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A4', 'Epic crossbow level 65', 10, true, false, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B4', 'Epic ring level 51', 11, true, false, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A5', 'Epic tank armor level 38', 12, true, false, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B5', 'Epic resurrect wand level 66', 13, true, false, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A20', '6 tickets', 14, true, true, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B20', '6 tickets', 15, true, true, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A21', '6 tickets', 16, true, true, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B21', '6 tickets', 17, true, true, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A17', '70 diamonds', 18, true, true, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B17', '70 diamonds', 19, true, true, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A18', '70 diamonds', 20, true, true, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B18', '70 diamonds', 21, true, true, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B12', '3 blue shards', 22, true, true, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A13', '3 blue shards', 23, true, true, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B13', '3 blue shards', 24, true, true, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A10', 'Green damage gem', 25, true, false, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B10', 'Green health gem', 26, true, false, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A19', '50 blue dust', 27, true, true, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B19', '500 green dust', 28, true, true, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A6', 'Rare crossbow level 54', 29, true, false, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B6', 'Rare ring level 60', 30, true, false, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A7', 'Rare tank armor level 54', 31, true, false, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B7', 'Rare amulet level 75', 32, true, false, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A8', 'Rare mage armor level 36', 33, true, false, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B8', 'Rare crossbob level 70', 34, true, false, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A9', 'Rare amulet level 67', 35, true, false, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B9', 'Rare ring level 62', 36, true, false, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A14', '4 green shards', 37, true, true, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B14', '4 green shards', 38, true, true, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A15', '4 green shards', 39, true, true, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B15', '4 green shards', 40, true, true, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A16', '4 green shards', 41, true, true, false, null, '2018-12-25', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B16', '4 green shards', 42, true, true, false, null, '2018-12-25', 1);


