insert into player (name, glory_points, loot_enabled, enabled, password, admin, clan_id) values ('Guest', 0, false, true, '', false, 1);
insert into player (name, glory_points, loot_enabled, enabled, password, admin, clan_id) values ('Sir Voyager', 0, true, true, 'password', true, 1);
insert into player (name, glory_points, loot_enabled, enabled, password, admin, clan_id) values ('TheAmazingLord', 0, true, true, '', false, 1);
insert into player (name, glory_points, loot_enabled, enabled, password, admin, clan_id) values ('DisabledPlayer', 0, false, false, '', false, 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('B01', 'Legendary archer armor level 62', 1, true, false, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('A01', 'Legendary archer armor level 59', 2, true, false, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('A11', '2 purple shards', 3, true, true, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('B11', '2 purple shards', 4, true, true, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('A04', 'Epic wand level 58', 5, true, false, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('A02', 'Epic armor level 73', 6, true, false, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('B02', 'Epic bow level 71', 7, true, false, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('B03', 'Epic archer armor level 52', 8, true, false, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('A03', 'Epic ring level 43', 9, true, false, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('B04', 'Epic tank armor level 74', 10, true, false, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('A05', 'Epic archer armor level 89', 11, true, false, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('B05', 'Epic archer armor level 56', 12, true, false, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('A12', '3 blue shards', 13, true, true, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('B12', '3 blue shards', 14, true, true, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('A13', '3 blue shards', 15, true, true, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('A18', '50 blue dust', 16, true, true, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('B18', '50 blue dust', 17, true, true, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('A19', '500 green dust', 18, true, true, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('B19', '6 tickets', 19, true, true, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('A20', '6 tickets', 20, true, true, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('B20', '6 tickets', 21, true, true, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('B16', '70 diamonds', 22, true, true, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('A17', '70 diamonds', 23, true, true, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('B17', '70 diamonds', 24, true, true, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('A10', 'Green damage gem', 25, true, false, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('B10', 'Green magic damage gem', 26, true, false, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('A06', 'Rare amulet level 55', 27, true, false, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('B06', 'Rare tank armor level 59', 28, true, false, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('A07', 'Rare archer level 75', 29, true, false, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('B07', 'Rare ring level 32', 30, true, false, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('A08', 'Rare ring level 53', 31, true, false, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('B08', 'Rare sword level 55', 32, true, false, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('A09', 'Rare ring level 59', 33, true, false, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('B09', 'Rare archer armor level 40', 34, true, false, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('B13', '4 green shards', 35, true, true, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('A14', '4 green shards', 36, true, true, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('B14', '4 green shards', 37, true, true, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('A15', '4 green shards', 38, true, true, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('B15', '4 green shards', 39, true, true, false, null, '2018-11-13');
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date) values ('A16', '4 green shards', 40, true, true, false, null, '2018-11-13');

