insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Guest', false, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Sir Voyager', true, true, 'password', true, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Domax', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Snotskovl', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Kongen', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Sir Spicion', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('BadAssBoss', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Brother', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('King Martin', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Baltazar', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Nicedam', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Aragon', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Holger Danske', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Tincan', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('NomaticDK', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Thhinuviel', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Sofus', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Chris', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Hammer', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Engberg', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('TheAmazingLord', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Casigan', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Dsk44', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Jig', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Baby kamyne', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Kipp', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Humack', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Ringle', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('HAMkamSAM', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Gnu', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Grgh', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('DasRotePferd', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Tim', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Moes', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Kook', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Pandekagemester', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Jinks', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('bSse', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Java', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Lord Julle', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Garm', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('King Marius', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Nick', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Master Nitten', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Nanna', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('ZoZoGamer', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('-!-Skum-!-', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Damp', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Sha', true, true, '', false, 1);
insert into player (name, loot_enabled, enabled, password, admin, clan_id) values ('Rasmus', true, true, '', false, 1);

insert into fruit (name) values ('Cherry');
insert into fruit (name) values ('Apple');
insert into fruit (name) values ('Banana');

insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', true, 1, 'Sir Voyager', '2018-12-11 23:55:00', 94717, 4);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', true, 1, 'Sir Voyager', '2018-12-11 23:55:00', 85854, 2);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', true, 1, 'Sir Voyager', '2018-12-11 23:55:00', 78552, 3);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', true, 1, 'Sir Voyager', '2018-12-11 23:55:00', 77138, 5);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', true, 1, 'Sir Voyager', '2018-12-11 23:55:00', 59657, 27);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', true, 1, 'Sir Voyager', '2018-12-11 23:55:00', 58717, 9);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', true, 1, 'Sir Voyager', '2018-12-11 23:55:00', 52714, 7);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', true, 1, 'Sir Voyager', '2018-12-11 23:55:00', 52018, 13);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', true, 1, 'Sir Voyager', '2018-12-11 23:55:00', 49767, 14);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', true, 1, 'Sir Voyager', '2018-12-11 23:55:00', 43401, 15);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', true, 1, 'Sir Voyager', '2018-12-11 23:55:00', 43263, 28);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', true, 1, 'Sir Voyager', '2018-12-11 23:55:00', 41812, 10);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', true, 1, 'Sir Voyager', '2018-12-11 23:55:00', 38374, 6);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', true, 1, 'Sir Voyager', '2018-12-11 23:55:00', 37976, 12);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', true, 1, 'Sir Voyager', '2018-12-11 23:55:00', 37468, 19);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', true, 1, 'Sir Voyager', '2018-12-11 23:55:00', 29123, 11);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', true, 1, 'Sir Voyager', '2018-12-11 23:55:00', 28921, 21);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', true, 1, 'Sir Voyager', '2018-12-11 23:55:00', 26016, 18);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', true, 1, 'Sir Voyager', '2018-12-11 23:55:00', 23277, 26);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', true, 1, 'Sir Voyager', '2018-12-11 23:55:00', 19232, 23);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', true, 1, 'Sir Voyager', '2018-12-11 23:55:00', 17360, 25);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', true, 1, 'Sir Voyager', '2018-12-11 23:55:00', 15580, 8);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', true, 1, 'Sir Voyager', '2018-12-11 23:55:00', 15571, 24);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', true, 1, 'Sir Voyager', '2018-12-11 23:55:00', 15247, 20);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', false, 1, 'Sir Voyager', '2018-12-11 23:55:00', 23638, 29);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', false, 1, 'Sir Voyager', '2018-12-11 23:55:00', 15192, 30);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', false, 1, 'Sir Voyager', '2018-12-11 23:55:00', 13555, 17);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', false, 1, 'Sir Voyager', '2018-12-11 23:55:00', 10530 , 16);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', false, 1, 'Sir Voyager', '2018-12-11 23:55:00', 10509, 39);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', false, 1, 'Sir Voyager', '2018-12-11 23:55:00', 10061, 34);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', false, 1, 'Sir Voyager', '2018-12-11 23:55:00', 9698, 31);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', false, 1, 'Sir Voyager', '2018-12-11 23:55:00', 8869, 32);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', false, 1, 'Sir Voyager', '2018-12-11 23:55:00', 8643, 36);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', false, 1, 'Sir Voyager', '2018-12-11 23:55:00', 8146, 33);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', false, 1, 'Sir Voyager', '2018-12-11 23:55:00', 7587, 38);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', false, 1, 'Sir Voyager', '2018-12-11 23:55:00', 7456, 35);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', false, 1, 'Sir Voyager', '2018-12-11 23:55:00', 7153, 37);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', false, 1, 'Sir Voyager', '2018-12-11 23:55:00', 6982, 41);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', false, 1, 'Sir Voyager', '2018-12-11 23:55:00', 6688, 40);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', false, 1, 'Sir Voyager', '2018-12-11 23:55:00', 3832, 42);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', false, 1, 'Sir Voyager', '2018-12-11 23:55:00', 3285, 43);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', false, 1, 'Sir Voyager', '2018-12-11 23:55:00', 2760, 44);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', false, 1, 'Sir Voyager', '2018-12-11 23:55:00', 2622, 47);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', false, 1, 'Sir Voyager', '2018-12-11 23:55:00', 1825, 22);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', false, 1, 'Sir Voyager', '2018-12-11 23:55:00', 1363, 45);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', false, 1, 'Sir Voyager', '2018-12-11 23:55:00', 600, 46);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', false, 1, 'Sir Voyager', '2018-12-11 23:55:00', 200, 48);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', false, 1, 'Sir Voyager', '2018-12-11 23:55:00', 0, 1);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', false, 1, 'Sir Voyager', '2018-12-11 23:55:00', 0, 49);
insert into glory_ranking (loot_date, eligible_for_loot, clan_id, updated_by, updated_ts, glory, fk_player_id) values ('2018-12-11', false, 1, 'Sir Voyager', '2018-12-11 23:55:00', 0, 50);

insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B1', 'Legendary amulet lever 83', 1, true, false, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A19', '6 tickets', 2, true, true, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A11', '2 purple shards', 3, true, true, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A2', 'Legendary mace level 61', 4, true, false, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A1', 'Legendary archer armor level 60', 5, true, false, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B2', 'Epic tank armor level 41', 6, true, false, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A3', 'Epic mage armor level 72', 7, true, false, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B3', 'Epic archer armor level 79', 8, true, false, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B5', 'Epic crossbow level 74', 9, true, false, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A4', 'Epic bow level 58', 10, true, false, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B4', 'Epic crossbow level 58', 11, true, false, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A5', 'Epic bow level 37', 12, true, false, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B11', '3 blue shards', 13, true, true, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A12', '3 blue shards', 14, true, true, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B12', '3 blue shards', 15, true, true, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A13', '3 blue shards', 16, true, true, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A18', '500 green dust', 17, true, true, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B18', '500 green dust', 18, true, true, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B16', '70 diamonds', 19, true, true, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A16', '70 diamonds', 20, true, true, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B19', '6 tickets', 21, true, true, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A20', '6 tickets', 22, true, true, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A17', '70 diamonds', 23, true, true, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B17', '50 blue dust', 24, true, true, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B10', 'Green armor gem', 25, true, false, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A10', 'Rare health scepter level 70', 26, true, false, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A6', 'Rare magic healing orb level 39', 27, true, false, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B6', 'Rare tank armor level 62', 28, true, false, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A7', 'Rare bow level 67', 29, true, false, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B7', 'Rare mage armor level 67', 30, true, false, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A8', 'Rare archer armor level 67', 31, true, false, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B8', 'Rare poleaxe level 67', 32, true, false, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A9', 'Rare magic ring level 60', 33, true, false, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B9', 'Rare crossbow level 62', 34, true, false, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B13', '4 green shards', 35, true, true, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A14', '4 green shards', 36, true, true, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B14', '4 green shards', 37, true, true, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A15', '4 green shards', 38, true, true, false, null, '2018-11-27', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B15', '4 green shards', 39, true, true, false, null, '2018-11-27', 1);

insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A1', 'Legendary Bow level 61', 1, true, false, false, null, '2018-12-11', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B1', 'Legendary Poleax level 45', 2, true, false, false, null, '2018-12-11', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A7', '2 Purple shards', 3, true, false, false, null, '2018-12-11', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B7', '2 Purple shards', 4, true, false, false, null, '2018-12-11', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A2', 'Epic Crossbow level 71', 5, true, false, false, null, '2018-12-11', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B2', 'Epic Sword level 51', 6, true, false, false, null, '2018-12-11', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A3', 'Epic Orb level 58', 7, true, false, false, null, '2018-12-11', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A8', '3 Blue shards', 8, true, false, false, null, '2018-12-11', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B8', '3 Blue shards', 9, true, false, false, null, '2018-12-11', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B12', '6 tickets', 10, true, false, false, null, '2018-12-11', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A13', '6 tickets', 11, true, false, false, null, '2018-12-11', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B13', '6 tickets', 12, true, false, false, null, '2018-12-11', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A11', '60 diamonds', 13, true, false, false, null, '2018-12-11', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B11', '60 diamonds', 14, true, false, false, null, '2018-12-11', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A12', '60 diamonds', 15, true, false, false, null, '2018-12-11', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B3', 'Rare Archer armor level 40', 16, true, false, false, null, '2018-12-11', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A4', 'Rare Scepter level 68', 17, true, false, false, null, '2018-12-11', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B4', 'Rare Scepter level 39', 18, true, false, false, null, '2018-12-11', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A5', 'Rare Mage armor Level 40', 19, true, false, false, null, '2018-12-11', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B5', 'Rare Amulet level 55', 20, true, false, false, null, '2018-12-11', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A6', 'Rare Ring level 76', 21, true, false, false, null, '2018-12-11', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B6', 'Rare Sword level 82', 22, true, false, false, null, '2018-12-11', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A9', '4 Green shards', 23, true, false, false, null, '2018-12-11', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B9', '4 Green shards', 24, true, false, false, null, '2018-12-11', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('A10', '4 Green shards', 25, true, false, false, null, '2018-12-11', 1);
insert into loot_item (row_and_num, name, priority_sequence, original, common, disabled, player_id, loot_date, clan_id) values ('B10', '4 Green shards', 26, true, false, false, null, '2018-12-11', 1);
